# Site settings
title: ARDOR Network
email: ardor-net@googlegroups.com
description: > # this means to ignore newlines until "baseurl:"
  Academic Researchers Developing Open Robotics
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  ardor-net

# Build settings
markdown: kramdown

# change this if moving to another server
github_client_id: 8dc5987c1028dd470a9a
github_gatekeeper_uri: http://ardor-net.herokuapp.com/authenticate/
